name: Pull request triggered workflow
run-name:  ${{ github.actor }} you created a pull request! 🏗️ # pull requests are used to create propose changes to the main code from another branch

on: 
  pull_request: # You think your code is good enough for the main code?
    branches: 
      main

jobs:
  pull-request-triggered: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "You created a PR and ran this"
          echo "The workflow result is: ${{ job.status }}" 

